require-crouch: true
ignore-tool-durability: false
require-tool: true
logs:
  - OAK_LOG
  - SPRUCE_LOG
  - BIRCH_LOG
  - JUNGLE_LOG
  - ACACIA_LOG
  - DARK_OAK_LOG
  - MANGROVE_LOG
  - CHERRY_LOG
  - CRIMSON_STEM
  - WARPED_STEM
  - SHROOMLIGHT