name: QuickFeller
version: 0.1
main: me.mattdokn.quickfeller.QuickFeller
api-version: 1.21
authors: [Mattdokn]
description: Tree feller plugin without drops.
website: https://www.youtube.com/channel/UCiwm6fobbKIUHR9EHG1EcVw
